using Content.Client.UserInterface.Controls;
using Content.Shared._Sandwich.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sandwich.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class AiNetworkMenu : FancyWindow
{
    public Action<NetEntity>? JumpPressed;

    public AiNetworkMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AiNetworkBuiState state)
    {
        EntryContainer.Children.Clear();

        foreach (var entry in state.Entries)
        {
            var button = new Button
            {
                Text = entry.Active ? entry.Name : $"{entry.Name} (offline)",
                HorizontalExpand = true,
                Disabled = !entry.Active,
                MinHeight = 32
            };

            var target = entry.Entity;
            button.OnPressed += _ => JumpPressed?.Invoke(target);

            EntryContainer.AddChild(button);
        }

        if (state.Entries.Count == 0)
        {
            EntryContainer.AddChild(new Label
            {
                Text = "No network connections.",
                HorizontalAlignment = HAlignment.Center
            });
        }
    }
}
