using Content.Client.Silicons.Borgs;
using Content.Client.UserInterface.Controls;
using Content.Shared._Sandwich.Silicons.StationAi;
using Content.Shared._Sandwich.Silicons.StationAi.Components;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sandwich.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class AiServerMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action<string>? NameChanged;
    public Action<EntityUid>? RemoveModuleButtonPressed;
    public Action? RemoveAuthIdCardPressed;
    public Action<EntityUid>? RemoveAuthKeyPressed;

    private string _lastValidName;
    private List<EntityUid> _modules = new();

    public EntityUid Entity;

    public AiServerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _lastValidName = NameLineEdit.Text;

        NameLineEdit.OnTextChanged += OnNameChanged;
        NameLineEdit.OnTextEntered += OnNameEntered;
        NameLineEdit.OnFocusExit += OnNameFocusExit;

        RightTabs.SetTabTitle(0, Loc.GetString("ai-server-ui-tab-modules"));
        RightTabs.SetTabTitle(1, Loc.GetString("ai-server-ui-tab-auth"));
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        NameLineEdit.Text = _entity.GetComponent<MetaDataComponent>(Entity).EntityName;
    }

    public void UpdateState(AiServerBuiState state)
    {
        if (state.HasLinkedCore && state.LinkedCore != null)
        {
            var coreUid = _entity.GetEntity(state.LinkedCore.Value);

            // Entity may not be resolved on client yet during state sync
            if (_entity.EntityExists(coreUid))
            {
                CoreSprite.SetEntity(coreUid);
                CoreStatusLabel.Text = _entity.GetComponent<MetaDataComponent>(coreUid).EntityName;
            }
            else
            {
                CoreSprite.SetEntity(null);
                CoreStatusLabel.Text = Loc.GetString("ai-server-ui-no-core");
            }
        }
        else
        {
            CoreSprite.SetEntity(null);
            CoreStatusLabel.Text = Loc.GetString("ai-server-ui-no-core");
        }

        UpdateModulePanel();
        UpdateAuthPanel(state);
    }

    private void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out AiNetworkServerComponent? server))
            return;

        ModuleCounter.Text = Loc.GetString("ai-server-ui-module-counter",
            ("actual", server.ModuleCount),
            ("max", server.MaxModules));

        if (server.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in server.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in server.ModuleContainer.ContainedEntities)
        {
            // Reuse the borg module control — it's just a sprite + name + remove button
            var control = new BorgModuleControl(module, _entity);
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }

    private void UpdateAuthPanel(AiServerBuiState state)
    {
        // Toggle visibility based on whether an Auth module is installed
        NoAuthLabel.Visible = !state.HasAuthModule;
        AuthContent.Visible = state.HasAuthModule;

        if (!state.HasAuthModule)
            return;

        // ID Card
        IdCardContainer.Children.Clear();
        if (state.AuthIdCard != null)
        {
            var cardUid = _entity.GetEntity(state.AuthIdCard.Value);
            if (_entity.EntityExists(cardUid))
            {
                var control = new BorgModuleControl(cardUid, _entity);
                control.RemoveButtonPressed += () =>
                {
                    RemoveAuthIdCardPressed?.Invoke();
                };
                IdCardContainer.AddChild(control);
            }
        }
        else
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("ai-auth-no-id-card"),
                Margin = new Robust.Shared.Maths.Thickness(5),
            };
            IdCardContainer.AddChild(emptyLabel);
        }

        // Encryption Keys
        KeysContainer.Children.Clear();
        if (state.AuthEncryptionKeys.Count > 0)
        {
            foreach (var keyNet in state.AuthEncryptionKeys)
            {
                var keyUid = _entity.GetEntity(keyNet);
                if (!_entity.EntityExists(keyUid))
                    continue;

                var control = new BorgModuleControl(keyUid, _entity);
                control.RemoveButtonPressed += () =>
                {
                    RemoveAuthKeyPressed?.Invoke(keyUid);
                };
                KeysContainer.AddChild(control);
            }
        }
        else
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("ai-auth-no-keys"),
                Margin = new Robust.Shared.Maths.Thickness(5),
            };
            KeysContainer.AddChild(emptyLabel);
        }
    }

    private void OnNameChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            return;
        }

        if (obj.Text.Length > HumanoidCharacterProfile.MaxNameLength)
        {
            obj.Control.Text = obj.Text.Substring(0, HumanoidCharacterProfile.MaxNameLength);
        }

        _lastValidName = obj.Control.Text;
        obj.Control.Text = _lastValidName;
    }

    private void OnNameEntered(LineEdit.LineEditEventArgs obj)
    {
        NameChanged?.Invoke(_lastValidName);
    }

    private void OnNameFocusExit(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length > HumanoidCharacterProfile.MaxNameLength ||
            obj.Text.Length == 0 ||
            string.IsNullOrWhiteSpace(obj.Text) ||
            string.IsNullOrEmpty(obj.Text))
        {
            obj.Control.Text = _lastValidName.Trim();
        }

        NameChanged?.Invoke(_lastValidName);
    }
}
