using Content.Shared._Sandwich.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Sandwich.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class BorisPairingMenu : FancyWindow
{
    public event Action<string>? OnSubmitCode;
    public event Action? OnUnpair;

    public BorisPairingMenu()
    {
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += _ =>
        {
            var code = CodeEntry.Text.Trim();
            if (code.Length == 4)
                OnSubmitCode?.Invoke(code);
        };

        UnpairButton.OnPressed += _ =>
        {
            OnUnpair?.Invoke();
        };
    }

    public void UpdateState(BorisBuiState state)
    {
        UnpairedPanel.Visible = !state.IsPaired;
        PairedPanel.Visible = state.IsPaired;

        if (state.IsPaired)
        {
            PairedLabel.Text = Loc.GetString("boris-paired-to", ("server", state.PairedServerName ?? "Unknown"));
        }

        CodeEntry.Text = string.Empty;
    }
}
