using Content.Shared._Sandwich.Silicons.StationAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Sandwich.Silicons.StationAi;

[GenerateTypedNameReferences]
public sealed partial class BorisControlMenu : FancyWindow
{
    public event Action<NetEntity>? OnTransferToborg;
    public event Action? OnReturnToCore;

    public BorisControlMenu()
    {
        RobustXamlLoader.Load(this);

        ReturnToCoreButton.OnPressed += _ =>
        {
            OnReturnToCore?.Invoke();
        };
    }

    public void UpdateState(BorisControlBuiState state)
    {
        PairingCodeLabel.Text = state.PairingCode;

        // Clear existing borg entries.
        BorgListContainer.RemoveAllChildren();

        var hasBorgs = state.PairedBorgs.Count > 0;
        NoBorgsLabel.Visible = !hasBorgs;

        foreach (var borg in state.PairedBorgs)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            var nameLabel = new Label
            {
                Text = borg.Name,
                HorizontalExpand = true
            };
            row.AddChild(nameLabel);

            // Only show transfer button if AI is not already in a borg.
            if (!state.IsTransferred)
            {
                var transferButton = new Button { Text = "Transfer" };
                var borgEntity = borg.Entity;
                transferButton.OnPressed += _ => OnTransferToborg?.Invoke(borgEntity);
                row.AddChild(transferButton);
            }
            else if (state.CurrentBorg == borg.Entity)
            {
                var currentLabel = new Label { Text = "[Current]" };
                row.AddChild(currentLabel);
            }

            BorgListContainer.AddChild(row);
        }

        // Show return button only when transferred.
        ReturnToCoreButton.Visible = state.IsTransferred;
    }
}
