using Content.Shared.Audio.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Audio.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private AudioSystem _audioSystem;

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<JukeboxPlaybackMode>? OnModeChanged; // Frontier
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;

    private EntityUid? _audio;

    private float _lockTimer;

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        StopButton.OnPressed += args =>
        {
            OnStopPressed?.Invoke();
        };
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;

        // Frontier: Shuffle & Repeat
        ShuffleButton.OnToggled += args =>
        {
            RepeatButton.Pressed = false;
            OnModeChanged?.Invoke(ShuffleButton.Pressed ? JukeboxPlaybackMode.Shuffle : JukeboxPlaybackMode.Single);
        };
        RepeatButton.OnToggled += args =>
        {
            ShuffleButton.Pressed = false;
            OnModeChanged?.Invoke(RepeatButton.Pressed ? JukeboxPlaybackMode.Repeat : JukeboxPlaybackMode.Single);
        };
        // End Frontier: Shuffle & Repeat

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
    }

    public JukeboxMenu(AudioSystem audioSystem)
    {
        _audioSystem = audioSystem;
    }

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes grouped by category and sorted alphabetically.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        MusicCategories.DisposeAllChildren();

        var uncategorised = Loc.GetString("jukebox-menu-category-uncategorised");
        var categories = new Dictionary<string, (string Category, List<JukeboxPrototype> Songs)>();

        foreach (var proto in jukeboxProtos)
        {
            var category = GetSongCategory(proto, uncategorised);
            var key = category.ToLowerInvariant();

            if (!categories.TryGetValue(key, out var entry))
            {
                entry = (category, new List<JukeboxPrototype>());
                categories[key] = entry;
            }

            entry.Songs.Add(proto);
            categories[key] = entry;
        }

        var orderedCategories = categories.Values
            .OrderBy(entry => entry.Category == uncategorised ? 1 : 0)
            .ThenBy(entry => entry.Category.ToLowerInvariant());

        foreach (var category in orderedCategories)
        {
            var songList = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(12, 0, 0, 4)
            };

            foreach (var proto in category.Songs.OrderBy(song => song.Name.ToLowerInvariant()))
            {
                var button = new Button
                {
                    Text = GetDisplayedSongName(proto),
                    HorizontalExpand = true
                };

                button.OnPressed += _ => OnSongSelected?.Invoke(proto.ID);
                songList.AddChild(button);
            }

            var body = new CollapsibleBody();
            body.AddChild(songList);

            var collapsible = new Collapsible(new JukeboxCategoryHeading(category.Category), body)
            {
                HorizontalExpand = true,
                BodyVisible = false
            };

            MusicCategories.AddChild(collapsible);
        }
    }

    public static string GetDisplayedSongName(JukeboxPrototype proto)
    {
        if (IsJukeboxPath(proto.Path.Path.ToString()))
            return proto.Name;

        return $"INVALID: {proto.Name}";
    }

    private static bool IsJukeboxPath(string path)
    {
        var pathParts = path.Replace('\\', '/').Split('/', StringSplitOptions.RemoveEmptyEntries);
        return Array.FindIndex(pathParts, part => string.Equals(part, "Jukebox", StringComparison.OrdinalIgnoreCase)) != -1;
    }

    private static string GetSongCategory(JukeboxPrototype proto, string uncategorised)
    {
        var path = proto.Path.Path.ToString().Replace('\\', '/');
        var pathParts = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        var jukeboxIndex = Array.FindIndex(pathParts, part => string.Equals(part, "Jukebox", StringComparison.OrdinalIgnoreCase));

        if (jukeboxIndex == -1 || jukeboxIndex >= pathParts.Length - 2)
            return uncategorised;

        return pathParts[jukeboxIndex + 1];
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        if (playing)
        {
            PlayButton.Text = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayButton.Text = Loc.GetString("jukebox-menu-buttonplay");
    }

    public void SetSelectedSong(string name, float length)
    {
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;
        PlaybackSlider.SetValueWithoutEvent(0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $"00:00 / 00:00";
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }

    // Frontier: Shuffle & Repeat
    public void UpdateState(BoundUserInterfaceState state)
    {
        if (state is not JukeboxInterfaceState convState)
            return;

        UpdateJukeboxButtons(convState);
    }

    private void UpdateJukeboxButtons(JukeboxInterfaceState state)
    {
        ShuffleButton.Pressed = state.PlaybackMode == JukeboxPlaybackMode.Shuffle;
        RepeatButton.Pressed = state.PlaybackMode == JukeboxPlaybackMode.Repeat;
    }
    // End Frontier: Shuffle & Repeat
}

public sealed class JukeboxCategoryHeading : CollapsibleHeading
{
    private readonly string _title;

    public JukeboxCategoryHeading(string title) : base(title)
    {
        _title = title;
        ChevronVisible = false;
        UpdateArrow(false);

        OnToggled += args =>
        {
            UpdateArrow(args.Pressed);
        };
    }

    private void UpdateArrow(bool expanded)
    {
        Title = expanded ? $"▼ {_title}" : $"▶ {_title}";
    }
}
